# SecretFlow Worker端函数输入参数格式设计
# 基于sf.init, spu.init, heu.init和任务执行参数的标准化格式

# 标准SecretFlow任务执行函数签名
# execute_secretflow_task(task_request_id: str, sf_init_config: dict, spu_config: dict, heu_config: dict, task_config: dict)

# 1. SecretFlow集群初始化配置 (sf.init所需参数)
sf_init_config:
  description: "SecretFlow集群初始化所需的核心参数"
  schema:
    parties:
      type: "list[str] | str"
      description: "参与计算的所有参与方标识列表，可以是字符串或字符串列表"
      example: ["alice", "bob"]
      required: false
      default: null
      
    ray_mode:
      type: "bool"
      description: "是否启用Ray模式进行分布式计算"
      default: true
      example: true
      
    address:
      type: "str"  
      description: "Ray集群地址，None时自动启动本地Ray集群"
      default: null
      example: "127.0.0.1:10001"
      optional: true
      
    cluster_config:
      type: "dict"
      description: "Ray集群的额外配置参数"
      default: null
      optional: true
      example: 
        logging_level: "info"
        enable_gpu: false
        
    num_cpus:
      type: "int"
      description: "分配给Ray集群的CPU核心数"
      default: null
      optional: true
      example: 8
      
    num_gpus:
      type: "int" 
      description: "分配给Ray集群的GPU设备数"
      default: null
      optional: true
      example: 0
      
    log_to_driver:
      type: "bool"
      description: "是否将日志输出到驱动程序"
      default: true
      example: true
      
    omp_num_threads:
      type: "int"
      description: "OpenMP线程数配置"
      default: null
      optional: true
      example: 4
      
    logging_level:
      type: "str"
      description: "日志记录级别"
      default: "info"
      options: ["debug", "info", "warning", "error", "critical"]
      example: "info"
      
    job_name:
      type: "str"
      description: "Ray作业名称标识"
      default: null
      optional: true
      example: "secretflow_job_001"
      
    cross_silo_comm_backend:
      type: "str"
      description: "跨数据孤岛通信后端协议"
      default: "grpc"
      options: ["grpc", "brpc_link", "http"]
      example: "grpc"
      
    cross_silo_comm_options:
      type: "dict"
      description: "跨孤岛通信的额外选项配置"
      default: null
      optional: true
      example:
        timeout_ms: 30000
        max_retry_times: 3
        
    enable_waiting_for_other_parties_ready:
      type: "bool"
      description: "是否等待其他参与方就绪后再开始计算"
      default: true
      example: true
      
    tls_config:
      type: "dict"
      description: "TLS安全通信配置，键为参与方名称"
      default: null
      optional: true
      example:
        alice:
          cert_path: "/path/to/alice.crt"
          key_path: "/path/to/alice.key" 
          ca_cert_path: "/path/to/ca.crt"
        bob:
          cert_path: "/path/to/bob.crt"
          key_path: "/path/to/bob.key"
          ca_cert_path: "/path/to/ca.crt"
          
    auth_manager_config:
      type: "dict"
      description: "认证管理器配置"
      default: null
      optional: true
      example:
        auth_method: "mtls"
        auth_timeout: 10
        
    party_key_pair:
      type: "dict"
      description: "参与方密钥对配置，键为参与方名称"
      default: null
      optional: true
      example:
        alice:
          public_key_path: "/path/to/alice_public.pem"
          private_key_path: "/path/to/alice_private.pem"
        bob:
          public_key_path: "/path/to/bob_public.pem" 
          private_key_path: "/path/to/bob_private.pem"
          
    tee_simulation:
      type: "bool"
      description: "是否启用可信执行环境(TEE)仿真模式"
      default: false
      example: false
      
    debug_mode:
      type: "bool"
      description: "是否启用调试模式，会输出更详细的调试信息"
      default: false
      example: false

# 2. SPU设备初始化配置 (spu.init所需参数)
spu_config:
  description: "安全处理单元(SPU)设备配置参数"
  schema:
    enable_spu:
      type: "bool"
      description: "是否启用SPU设备，某些任务可能不需要SPU"
      default: true
      
    runtime_config:
      type: "dict"
      description: "SPU运行时配置"
      required_when_enabled: true
      schema:
        protocol:
          type: "str"
          description: "多方安全计算协议"
          options: ["SEMI2K", "ABY3", "CHEETAH"]
          example: "SEMI2K"
          
        field:
          type: "str" 
          description: "有限域配置"
          options: ["FM64", "FM128"]
          example: "FM128"
          
    link_desc:
      type: "dict"
      description: "SPU网络连接描述配置"
      required_when_enabled: true
      schema:
        connect_retry_times:
          type: "int"
          description: "连接重试次数"
          default: 60
          
        connect_retry_interval_ms:
          type: "int"
          description: "重试间隔(毫秒)"
          default: 1000
          
        brpc_channel_protocol:
          type: "str"
          description: "BRPC通道协议"
          default: "http"
          options: ["http", "baidu_std", "hulu_pbrpc"]
          
        brpc_channel_connection_type:
          type: "str"
          description: "BRPC连接类型"
          default: "pooled"
          options: ["single", "pooled", "short"]
          
        recv_timeout_ms:
          type: "int"
          description: "接收超时时间(毫秒)"
          default: 1200000
          
        http_timeout_ms:
          type: "int"
          description: "HTTP超时时间(毫秒)" 
          default: 1200000
  # 等其他SPU参数

# 3. HEU设备初始化配置 (heu.init所需参数)
heu_config:
  description: "同态加密单元(HEU)设备配置参数"
  schema:
    enable_heu:
      type: "bool"
      description: "是否启用HEU设备，某些任务可能不需要HEU"
      default: true
      
    mode:
      type: "str"
      description: "同态加密模式"
      options: ["PHEU", "FHEU"]
      default: "PHEU"
      example: "PHEU"
      
    schema:
      type: "str"
      description: "同态加密方案"
      options: ["paillier", "ou", "ec_elgamal"]
      default: "paillier"
      example: "paillier"
      
    key_size:
      type: "int"
      description: "密钥长度(位)"
      options: [1024, 2048, 3072, 4096]
      default: 2048
      example: 2048
  # 等其他HEU参数

# 4. 任务特定配置 (根据不同任务类型变化)
task_config:
  description: "具体任务执行所需的参数配置"
  schema:
    task_type:
      type: "str"
      description: "任务类型标识"
      required: true
      examples: ["psi", "pir", "lr", "xgb", "nn"]
      
    domain:
      type: "str"
      description: "任务所属领域"
      required: true
      examples: ["data_prep", "ml.train", "ml.predict", "stats"]
      
    version:
      type: "str"
      description: "任务算法版本"
      default: "1.0.0"
      
    # 输入数据配置
    input_data:
      type: "dict"
      description: "输入数据配置"
      required: true
      schema:
        type: "dict"
        description: "各参与方数据源配置映射"
        example:
          alice: 
            data_path: "/data/alice/alice-data.csv"
          bob:
            data_path: "/data/bob/bob-data.csv"
    
    # 输出数据配置  
    output_data:
      type: "dict"
      description: "输出数据配置"
      required: true
      schema:
          type: "dict"
          description: "各参与方数据源配置映射"
          example:
            alice: 
              data_path: "/data/alice/alice-data-output.csv"
            bob:
              data_path: "/data/bob/bob-data-output.csv"
    
    # 算法特定参数 (根据task_type动态变化)
    algorithm_params:
      type: "dict"
      description: "算法特定的执行参数，内容根据task_type变化"
      required: true
      
      # PSI任务示例参数
      psi_params_example:
        input_keys:
          alice_keys: ["id1"]
          bob_keys: ["id2"]
        protocol: "PROTOCOL_RR22"
        sort_result: true
        join_type: "inner_join"
        receiver_parties: ["alice", "bob"]
        allow_duplicated_keys: 
          alice: true
          bob: true
        allow_empty_result: true
        
      # 机器学习训练任务示例参数
      ml_train_params_example:
        model_type: "logistic_regression"
        features: ["feature1", "feature2", "feature3"]
        label: "target"
        training_params:
          learning_rate: 0.01
          max_iter: 100
          reg_type: "l2"
          reg_lambda: 0.1

# 5. Worker端状态通信配置
worker_status_config:
  description: "Worker端任务状态通信配置，集成现有Redis监听系统"
  schema:
    task_request_id:
      type: "str"
      description: "任务请求唯一标识符"
      required: true
      
    enable_status_reporting:
      type: "bool"
      description: "是否启用状态上报"
      default: true
      
    status_report_interval:
      type: "int"
      description: "状态上报间隔(秒)"
      default: 30
      
    redis_config:
      type: "dict"
      description: "Redis通信配置"
      schema:
        redis_url:
          type: "str"
          description: "Redis连接URL"
          example: "redis://redis:6379/0"
          
        status_channel:
          type: "str"  
          description: "状态发布频道"
          default: "task_status_events"
          
        status_queue:
          type: "str"
          description: "状态队列名称"
          default: "task_status_queue"
          
        worker_container_id:
          type: "str"
          description: "Worker容器标识"
          example: "secretflow-worker-1"

# 完整函数调用示例
function_call_example:
  description: "SecretFlow Worker端任务执行函数的完整调用示例"
  
  # PSI任务示例
  psi_task_example:
    task_request_id: "uuid-12345-67890"
    
    sf_init_config:
      parties: ["alice", "bob"]
      ray_mode: true
      address: "127.0.0.1:10001"
      cluster_config: null
      num_cpus: 4
      num_gpus: 0
      log_to_driver: true
      omp_num_threads: null
      logging_level: "info"
      job_name: "psi_task_001"
      cross_silo_comm_backend: "grpc"
      cross_silo_comm_options: null
      enable_waiting_for_other_parties_ready: true
      tls_config: null
      auth_manager_config: null
      party_key_pair: null
      tee_simulation: false
      debug_mode: false
      
    spu_config:
      enable_spu: true
      runtime_config:
        protocol: "SEMI2K"
        field: "FM128"
      link_desc:
        connect_retry_times: 60
        connect_retry_interval_ms: 1000
        brpc_channel_protocol: "http"
        brpc_channel_connection_type: "pooled"
        recv_timeout_ms: 1200000
        http_timeout_ms: 1200000
        
    heu_config:
      enable_heu: true
      mode: "PHEU"
      schema: "paillier"
      key_size: 2048
      
    task_config:
      task_type: "psi"
      domain: "data_prep"
      version: "1.0.0"
      input_data:
        alice:
          data_path: "/data/alice/ml/data-alice.csv"
        bob:
          data_path: "/data/bob/ml/data-bob.csv"
      output_data:
        alice:
          data_path: "/data/alice/ml/data-alice-output.csv"
        bob:
          data_path: "/data/bob/ml/data-bob-output.csv"
      algorithm_params:
        input_keys:
          alice_keys: ["id1"]
          bob_keys: ["id2"]
        protocol: "PROTOCOL_RR22"
        sort_result: true
        join_type: "inner_join"
        receiver_parties: ["alice", "bob"]
        allow_duplicated_keys:
          alice: true
          bob: true
        allow_empty_result: true
  
  # 仅需要SPU的机器学习任务示例
  ml_task_example:
    task_request_id: "uuid-ml-11111"
    
    sf_init_config:
      parties: ["alice", "bob", "charlie"]
      ray_mode: true
      address: "127.0.0.1:10001"
      cluster_config:
        logging_level: "info"
        enable_gpu: false
      num_cpus: 8
      num_gpus: 0
      log_to_driver: true
      omp_num_threads: 4
      logging_level: "info"
      job_name: "ml_train_task_001"
      cross_silo_comm_backend: "grpc"
      cross_silo_comm_options:
        timeout_ms: 60000
        max_retry_times: 5
      enable_waiting_for_other_parties_ready: true
      tls_config: null
      auth_manager_config: null
      party_key_pair: null
      tee_simulation: false
      debug_mode: false
      
    spu_config:
      enable_spu: true
      runtime_config:
        protocol: "ABY3"  # 三方协议
        field: "FM128"
      link_desc:
        connect_retry_times: 60
        connect_retry_interval_ms: 1000
        brpc_channel_protocol: "http"
        brpc_channel_connection_type: "pooled"
        recv_timeout_ms: 1800000  # 30分钟，ML任务通常耗时更长
        http_timeout_ms: 1800000
        
    heu_config:
      enable_heu: false  # ML训练任务可能不需要HEU
      
    task_config:
      task_type: "lr"
      domain: "ml.train"
      version: "1.0.0"
      input_data:
        alice:
          data_path: "/data/alice/ml/train-data-alice.csv"
        bob:
          data_path: "/data/bob/ml/train-data-bob.csv"
        charlie:
          data_path: "/data/charlie/ml/train-data-charlie.csv"
      output_data:
        alice:
          data_path: "/data/alice/ml/train-data-alice-output.csv"
        bob:
          data_path: "/data/bob/ml/train-data-bob-output.csv"
        charlie:
          data_path: "/data/charlie/ml/train-data-charlie-output.csv"
      algorithm_params:
        features: ["age", "income", "education"]
        label: "credit_score"
        training_params:
          learning_rate: 0.01
          max_iter: 100
          reg_type: "l2"
          reg_lambda: 0.1
          batch_size: 1000

# 参数验证规则
validation_rules:
  description: "输入参数的验证规则和约束"
  
  sf_init_validation:
    - "parties可以为null、字符串或字符串列表，如果提供则参与方名称必须唯一"
    - "ray_mode为false时将使用本地模式，不启动Ray集群"
    - "address为null时自动启动本地Ray集群，否则必须是有效的Ray地址格式(如127.0.0.1:10001)"
    - "num_cpus和num_gpus应根据实际硬件资源合理设置，避免超分配"
    - "logging_level必须是有效的日志级别：debug, info, warning, error, critical"
    - "cross_silo_comm_backend应根据网络环境选择：grpc适合一般场景，brpc_link适合高性能场景"
    - "tls_config启用时，所有参与方都必须提供相应的证书文件路径"
    - "party_key_pair启用时，必须为每个参与方提供公钥和私钥文件路径"
    - "debug_mode仅在开发测试环境使用，生产环境应设为false"
    
  spu_validation:
    - "当enable_spu为true时，runtime_config和link_desc必须提供"
    - "protocol必须与参与方数量匹配(SEMI2K适用2方，ABY3适用3方)"
    - "超时时间应根据任务复杂度合理设置"
    
  heu_validation:
    - "当enable_heu为true时，mode、schema、key_size必须提供"
    - "key_size越大安全性越高但性能越低，需要平衡考虑"
    
  task_validation:
    - "task_type必须是系统支持的任务类型"
    - "input_ids和data_sources的参与方必须与sf_init_config.parties一致"
    - "algorithm_params内容必须符合对应task_type的参数要求"